services:
  - type: web
    name: mtech-chatbot-api
    runtime: python
    pythonVersion: "3.9"
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p ./knowledge_base
    startCommand: gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: README_DIR
        value: ./knowledge_base
      - key: PORT
        value: 10000
      - key: RELOAD
        value: "false"
      - key: TRANSFORMERS_OFFLINE
        value: "1"
      - key: PYTORCH_CUDA_ALLOC_CONF
        value: "max_split_size_mb:32"
      - key: WEB_CONCURRENCY
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
