services:
  - type: web
    name: mtech-chatbot-api
    runtime: python
    pythonVersion: "3.9"
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p ./knowledge_base
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 4000 --workers 1
    envVars:
      - key: README_DIR 
        value: ./knowledge_base
      - key: PORT
        value: 10000
      - key: RELOAD
        value: "false"
